### ISSUE TITLE
Error on start docker container 

### ISSUE THREAD

**Issue by RodzynBWA** [kaimallea/csgo#9] opened 2018-07-14 08:04 UTC
Hi guys! :P I got an error on docker container start:

exec: "./start.sh": stat ./start.sh: no such file or directory

I'm using rancher 1.6 but I did everything ok ;)

How Can I fix it ? :D

**Comment by kaimallea** [comment] 2018-07-14 22:14
Can you share the exact command you're using to run the container? Also, I'm not familiar with rancher? A quick search reveals  that it is for container management. What happens if you try to run it without rancher, just as a test?

**Comment by kaimallea** [comment] 2018-07-22 03:40
Closing as I cannot reproduce and it seems specific to rancher. Feel free to re-open if you find that to be inaccurate.

**Closed by kaimallea** 2018-07-22 03:40 UTC
